services:
  - type: web
    name: sistemas-gerenciador-rm
    env: python
    buildCommand: |
      bash -c "
      apt-get update &&
      apt-get install -y curl gnupg2 apt-transport-https unixodbc unixodbc-dev &&
      curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&
      curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list &&
      apt-get update &&
      ACCEPT_EULA=Y apt-get install -y msodbcsql17 &&
      echo '[ODBC Driver 17 for SQL Server]' > /etc/odbcinst.ini &&
      echo 'Description=Microsoft ODBC Driver 17 for SQL Server' >> /etc/odbcinst.ini &&
      echo 'Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.X.so' >> /etc/odbcinst.ini &&
      echo 'UsageCount=1' >> /etc/odbcinst.ini &&
      pip install -r requirements.txt
      "
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
