services:
  - type: web
    name: sistemas-gerenciador-rm
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y curl gnupg2 apt-transport-https unixodbc unixodbc-dev && \
      curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
      curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
      apt-get update && \
      ACCEPT_EULA=Y apt-get install -y msodbcsql17 && \
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
